### ISSUE TITLE
Каталог данных "/var/lib/postgresql/data" имеет недопустимые разрешения

### ISSUE THREAD

**Issue by NetilogyIvan** [NetilogyIvan/work_1_PostgreSQL#1]
# Описание
При запуске docker-compose.yml командой "docker-compose up" происходит обрушение сборки 

# Локация дефекта
https://github.com/NetilogyIvan/work_1_PostgreSQL/blob/9ea81af2b31579704a0977a4d331a490c44cee5d/docker-compose.yml#L8

# Шаги воспроизведения
1. Запустить Docker desktop, убедится в наличии соединения. 
2. Запустить [приложение к тестированию на СУБД](https://github.com/NetilogyIvan/work_1_PostgreSQL.git) в IDEA.
3. Открыть terminal в IDEA.
4. Ввести команду "docker-compose up" 

###  Ожидаемый результат:
Сборка образа и вывод сообщения "database system is ready to accept connections" 
### Фактический результат:
Обрушение сборки, вывод сообщений: 
"FATAL:  data directory "/var/lib/postgresql/data" has invalid permissions"
"DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750)."
"child process exited with exit code 1"

# Скриншот:
![image](https://github.com/NetilogyIvan/work_1_PostgreSQL/assets/125291269/58965d1d-b0ed-40c1-997a-581a82c665ff)

# Окружение 
* **Операционная система:** Windows 10 версия 22H2
* **IDE:** IntelliJ IDEA 2022.3.2
* **JAVA:** openjdk 11.0.17 2022-10-18
* **Docker:** Desktop 4.21.1

**Comment by andrew-pahomov** [comment]
Покажите содержимое папки проекта

**Comment by NetilogyIvan** [comment]
Содержимое папки проекта можно посмотреть по ссылке:
[весь проект](https://github.com/NetilogyIvan/work_1_PostgreSQL)
